Allow revision instead of HEAD

diff --git a/git-branch-from-cherry b/git-branch-from-cherry
--- a/git-branch-from-cherry
+++ b/git-branch-from-cherry
@@ -76,10 +76,10 @@ if [ "$MOVE_BRANCH" ]; then
     MOVE_BRANCH="git reset --hard HEAD^^^"
   elif echo "$*" | grep -i '^HEAD (HEAD^$|HEAD~1)$' >/dev/null; then
     MOVE_BRANCH="git reset --hard HEAD^^"
-  elif echo "$*" | grep -i '^HEAD$' >/dev/null; then
+  elif echo "$*" | grep -i '^HEAD$' >/dev/null || [ "`git rev-parse $*`" == "`git rev-parse HEAD`" ]; then
     MOVE_BRANCH="git reset --hard HEAD^"
   else
-    echo "error: cannot use -b with this pattern. Aborting." >&2
+    echo "error: cannot use -b with this cherry-pick pattern. Aborting." >&2
     exit 1
   fi
 fi
